spring:
  main:
    web-application-type: NONE
  jackson:
    serialization:
      indent_output: true

dollar-sign: "$"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%20.20t]){faint} %clr(%-50.50logger{49}){cyan} %clr(:){faint} %m%n%wEx"

web:
  game:
    base-path: /index.php/1001
    version-path: /Index/version
  cdn:
    base-path: /data

client:
  clients:
    - region: us
      game-host: http://gf-game.sunborngame.com
      cdn-host: http://gfus-cdn.sunborngame.com
      dump-version: 20702
    - region: jp
      game-host: http://gfjp-game.sunborngame.com
      cdn-host: http://gfjp-cdn.sunborngame.com
      dump-version: 20701
    - region: kr
      game-host: http://gf-game.girlfrontline.co.kr
      cdn-host: http://gfkrcdn.imtxwy.com
      dump-version: 20801
    - region: tw
      game-host: http://sn-game.txwy.tw
      cdn-host: http://sncdn.imtxwy.com
      dump-version: 20801

file:
  charset: UTF-8
  base-path: ./target/gfl-data
  output-path: ${file.base-path}/out
  json:
    extension: .json
  stc:
    path: ${file.base-path}/${dollar-sign}{region}/stc
    extract-path: ${file.base-path}/${dollar-sign}{region}/stc/extract
    output-path: ${file.output-path}/${dollar-sign}{region}/stc
    catchdata-encryption-key: c88d016d261eb80ce4d6e41a510d4048
    catchdata-line-separator: "\n"
    catchdata-output-path: ${file.stc.output-path}/catchdata
    mapping-path: classpath:stc-mapping/${dollar-sign}{region}/*.json
    skip:
      - 5122.stc
      - 5123.stc
  dump-data-version-path: ${file.output-path}/latest-versions${file.json.extension}

git:
  remote-url: https://github.com/neko-gg/gfl-data.git
  directory: ${file.base-path}/gfl-data-repo
  git-directory: ${git.directory}/.git
  token: ${API_TOKEN_GITHUB}
  username: gfl-data-miner
  email: gfl-data-miner@neko.gg
  latest-versions-commit-message: update latest versions
  region-commit-message: "[${dollar-sign}{region}] client ${dollar-sign}{client-version} | ab ${dollar-sign}{ab-version} | data ${dollar-sign}{data-version}"

string-substitutor:
  prefix: "${"
  suffix: "}"
  values:
    region: region
    client-version: client-version
    ab-version: ab-version
    data-version: data-version
