name: gfl-data-miner

on:
  schedule:
    - cron: '42 */6 * * *'
  workflow_dispatch:

jobs:
  gfl-data-miner-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: pip install -Iv UnityPy==1.7.13
      - name: Build with Maven
        run: mvn clean install -B
      - name: Run Spring Boot application
        run: mvn spring-boot:run -B
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
