name: gfl-data-miner

on:
  push:
    branches: [ senpai ]
  pull_request:
    branches: [ senpai ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -B
    - name: Run Spring Boot application
      run: mvn spring-boot:run -B
    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: '/tmp/gfl-data-miner'
        destination-github-username: 'neko-gg'
        destination-repository-name: 'gfl-data'
        user-email: gfl-data-miner@neko.gg
        commit-message: gfl-data-miner auto update
        target-branch: senpai
